import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { SysMLv2GeneratedModule, SysMLv2GeneratedSharedModule } from './generated/module';
import { SysMLv2ValidationRegistry, SysMLv2Validator } from './sysml-v2-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SysMLv2AddedServices = {
    validation: {
        SysMLv2Validator: SysMLv2Validator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SysMLv2Services = LangiumServices & SysMLv2AddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SysMLv2Module: Module<SysMLv2Services, PartialLangiumServices & SysMLv2AddedServices> = {
    validation: {
        ValidationRegistry: (services) => new SysMLv2ValidationRegistry(services),
        SysMLv2Validator: () => new SysMLv2Validator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSysMLv2Services(context?: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SysMLv2: SysMLv2Services
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SysMLv2GeneratedSharedModule
    );
    const SysMLv2 = inject(
        createDefaultModule({ shared }),
        SysMLv2GeneratedModule,
        SysMLv2Module
    );
    shared.ServiceRegistry.register(SysMLv2);
    return { shared, SysMLv2 };
}
